name: Build and Deploy

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:   # omogoča ročni zagon

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install Quasar CLI
      run: npm install -g @quasar/cli

    - name: Install dependencies
      run: npm ci

    - name: Build (Quasar)
      run: npm run build

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages    # kam objavi
        folder: dist/spa    # Quasar output
